spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} #Environment variable
  datasource:
    url: ${datasource-url} #Secret from Azure Key Vault
    username: ${datasource-username} #Secret from Azure Key Vault
    password: ${datasource-password} #Secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none #Turn off the DDL auto generation.
ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions} #The environment variable with a default value
    api-key: ${ai-openai-api-key:your-openai-api-key} #This is a secret from Azure Key Vault